export const currencyNames = {
  Bitcoin: 'BTC',
  Euro: 'EUR',
  'US Dollar': 'USD',
  'Argentine Peso': 'ARS',
  'Japanese Yen': 'JPY',
  'Chinese Yuan': 'CNY',
  'Australian Dollar': 'AUD',
  'Canadian Dollar': 'CAD',
  'Liberian Dollar': 'LRD',
}

export const banks = [
  {
    id: '1',
    name: 'МТБАНК',
    description: 'просп. Черняховского, 6, Витебск',
    coordinates: { lat: 55.181032, lng: 30.202741 },
    currencies: ['ARS', 'LRD', 'BTC', 'JPY', 'AUD', 'CNY'],
  },
  {
    id: '2',
    name: 'Paritetbank',
    description: 'пр. Гоголя, 11, Витебск',
    coordinates: { lat: 55.186329, lng: 30.202531 },
    currencies: ['ARS'],
  },
  {
    id: '3',
    name: 'Банк РРБ',
    description: 'Московский просп., 8 РРБ, Витебск',
    coordinates: { lat: 55.183624, lng: 30.206267 },
    currencies: ['AUD', 'CNY', 'LRD', 'ARS'],
  },
  {
    id: '4',
    name: 'Приорбанк',
    description: 'ул. Толстого, 3, Витебск',
    coordinates: { lat: 55.195131, lng: 30.204748 },
    currencies: ['JPY', 'CAD', 'AUD', 'USD', 'BTC', 'ARS'],
  },
  {
    id: '5',
    name: 'Paritetbank',
    description: 'Московский просп., 12, Витебск',
    coordinates: { lat: 55.182343, lng: 30.207393 },
    currencies: ['JPY', 'LRD', 'CNY', 'BTC', 'CAD', 'USD', 'EUR', 'AUD'],
  },
  {
    id: '6',
    name: 'МТБАНК',
    description: 'ул. Ленина, 12А, Витебск',
    coordinates: { lat: 55.18749, lng: 30.204429 },
    currencies: ['BTC', 'CNY', 'CAD', 'AUD', 'LRD', 'ARS'],
  },
  {
    id: '7',
    name: 'Беларусбанк',
    description: 'Московский просп., 7, Витебск',
    coordinates: { lat: 55.181633, lng: 30.205261 },
    currencies: ['EUR', 'LRD', 'JPY', 'AUD', 'BTC'],
  },
  {
    id: '8',
    name: 'Белорусский народный банк',
    description: 'ул. Толстого, 4, Витебск',
    coordinates: { lat: 55.194918, lng: 30.20486 },
    currencies: ['LRD', 'AUD', 'ARS', 'EUR', 'CAD'],
  },
  {
    id: '9',
    name: 'Белинвестбанк',
    description: 'ул. Ленина, 22, Витебск',
    coordinates: { lat: 55.189922, lng: 30.205293 },
    currencies: ['BTC', 'CNY', 'EUR', 'ARS', 'LRD', 'CAD', 'AUD', 'USD'],
  },
  {
    id: '10',
    name: 'Приорбанк',
    description: 'просп. Строителей, 11А, Витебск',
    coordinates: { lat: 55.171055, lng: 30.215285 },
    currencies: ['ARS', 'USD', 'BTC', 'AUD'],
  },
  {
    id: '11',
    name: 'БЕЛВЭБ',
    description: 'ул. Димитрова, 11, Витебск',
    coordinates: { lat: 55.194617, lng: 30.192013 },
    currencies: ['ARS', 'AUD', 'JPY'],
  },
  {
    id: '12',
    name: 'Белагропромбанк',
    description: 'ул. Димитрова, 31, Витебск',
    coordinates: { lat: 55.187714, lng: 30.190132 },
    currencies: ['CAD', 'AUD', 'CNY', 'BTC', 'ARS'],
  },
  {
    id: '13',
    name: 'Беларусбанк',
    description: 'Замковая ул., 30, Витебск',
    coordinates: { lat: 55.192461, lng: 30.205963 },
    currencies: ['CAD', 'EUR', 'AUD', 'CNY', 'USD'],
  },
  {
    id: '14',
    name: 'Белгазпромбанк',
    description: 'просп. Строителей, 1Г, Витебск',
    coordinates: { lat: 55.17262, lng: 30.202814 },
    currencies: ['CNY', 'EUR', 'USD', 'LRD', 'JPY', 'ARS', 'CAD', 'BTC', 'AUD'],
  },
  {
    id: '15',
    name: 'Белагропромбанк',
    description: 'Московский просп., 31А, Витебск',
    coordinates: { lat: 55.178586, lng: 30.223259 },
    currencies: ['BTC', 'CNY'],
  },
  {
    id: '16',
    name: 'Сбер Банк',
    description: 'ул. Ленина, 26, Витебск',
    coordinates: { lat: 55.190754, lng: 30.205601 },
    currencies: ['EUR', 'AUD', 'CAD', 'CNY', 'ARS', 'LRD', 'BTC'],
  },
  {
    id: '17',
    name: 'МТБАНК',
    description: 'просп. Строителей, 15В, Витебск',
    coordinates: { lat: 55.170451, lng: 30.220368 },
    currencies: ['BTC', 'EUR', 'AUD', 'LRD'],
  },
  {
    id: '18',
    name: 'Альфа-Банк',
    description: 'улица Космонавтов, 11, Витебск',
    coordinates: { lat: 55.195812, lng: 30.188963 },
    currencies: ['BTC', 'EUR', 'AUD', 'LRD', 'USD', 'CAD', 'ARS', 'CNY', 'JPY'],
  },
  {
    id: '19',
    name: 'Белагропромбанк',
    description: 'улица Толстого, 2, Витебск',
    coordinates: { lat: 55.194731, lng: 30.205609 },
    currencies: ['BTC', 'EUR', 'JPY', 'CAD', 'ARS', 'AUD'],
  },
  {
    id: '20',
    name: 'Беларусбанк, ипотечный офис',
    description: 'Московский просп., 8А, Витебск',
    coordinates: { lat: 55.183652, lng: 30.206944 },
    currencies: ['LRD', 'JPY', 'EUR', 'CAD', 'ARS', 'USD', 'AUD', 'CNY', 'BTC'],
  },
  {
    id: '21',
    name: 'Белинвестбанк',
    description: 'ул. Космонавтов, 8, Витебск',
    coordinates: { lat: 55.194995, lng: 30.186047 },
    currencies: ['CAD', 'EUR', 'JPY', 'CNY'],
  },
  {
    id: '22',
    name: 'Беларусбанк',
    description: 'Смоленская ул., 9А, Витебск',
    coordinates: { lat: 55.185255, lng: 30.232679 },
    currencies: ['AUD', 'CNY', 'CAD', 'USD', 'EUR', 'JPY', 'LRD', 'BTC', 'ARS'],
  },
  {
    id: '23',
    name: 'Беларусбанк',
    description: 'ул. Кирова, 10, Витебск',
    coordinates: { lat: 55.194273, lng: 30.19314 },
    currencies: ['LRD', 'BTC', 'CAD', 'CNY'],
  },
  {
    id: '24',
    name: 'Беларусбанк',
    description: 'просп. Строителей, 12, Витебск',
    coordinates: { lat: 55.171514, lng: 30.222947 },
    currencies: ['BTC', 'AUD', 'JPY', 'EUR'],
  },
  {
    id: '25',
    name: 'Беларусбанк',
    description: 'ул. Ленина, 10Б, Витебск',
    coordinates: { lat: 55.18773, lng: 30.202533 },
    currencies: ['BTC', 'CNY', 'USD', 'EUR', 'AUD', 'JPY', 'ARS', 'CAD'],
  },
  {
    id: '26',
    name: 'Белагропромбанк',
    description: 'проспект Строителей, 12, Витебск',
    coordinates: { lat: 55.171204, lng: 30.222049 },
    currencies: ['CNY', 'LRD', 'CAD', 'JPY', 'BTC', 'USD', 'AUD', 'EUR', 'ARS'],
  },
  {
    id: '27',
    name: 'Белинвестбанк',
    description: 'Московский проспект, 33, Витебск',
    coordinates: { lat: 55.177602, lng: 30.227008 },
    currencies: ['CNY', 'JPY', 'LRD', 'EUR', 'CAD', 'BTC', 'ARS', 'USD', 'AUD'],
  },
  {
    id: '28',
    name: 'Альфа-Банк',
    description: 'проспект Строителей, 15к1, Витебск',
    coordinates: { lat: 55.170175, lng: 30.222692 },
    currencies: ['EUR', 'CNY', 'CAD', 'JPY', 'LRD', 'BTC', 'AUD'],
  },
  {
    id: '29',
    name: 'Белагропромбанк',
    description: 'улица Ленина, 10А, Витебск',
    coordinates: { lat: 55.187541, lng: 30.204088 },
    currencies: ['USD'],
  },
  {
    id: '30',
    name: 'Банк Дабрабыт',
    description: 'проспект Фрунзе, 35к1, Витебск',
    coordinates: { lat: 55.193304, lng: 30.22499 },
    currencies: ['LRD', 'USD', 'AUD', 'EUR'],
  },
  {
    id: '31',
    name: 'Технобанк',
    description: 'улица Ленина, 61, Витебск',
    coordinates: { lat: 55.19991, lng: 30.207604 },
    currencies: ['EUR', 'BTC', 'AUD', 'USD', 'JPY', 'CAD', 'LRD'],
  },
  {
    id: '32',
    name: 'Альфа-Банк',
    description: 'проспект Генерала Людникова, 16А, Витебск',
    coordinates: { lat: 55.195772, lng: 30.228252 },
    currencies: ['BTC', 'USD', 'EUR'],
  },
  {
    id: '33',
    name: 'Беларусбанк',
    description: 'улица Берестеня, 7, Витебск',
    coordinates: { lat: 55.198078, lng: 30.239934 },
    currencies: ['LRD', 'CAD', 'USD', 'CNY', 'EUR', 'ARS', 'BTC', 'AUD'],
  },
  {
    id: '34',
    name: 'Paritetbank',
    description: 'Московский проспект, 12, Витебск',
    coordinates: { lat: 55.18234, lng: 30.20739 },
    currencies: ['CAD'],
  },
  {
    id: '35',
    name: 'Белинвестбанк',
    description: 'улица Ленина, 26А, Витебск',
    coordinates: { lat: 55.191492, lng: 30.20363 },
    currencies: ['ARS', 'JPY'],
  },
  {
    id: '36',
    name: 'БТА банк',
    description: 'Советская улица, 19, Витебск',
    coordinates: { lat: 55.199359, lng: 30.205979 },
    currencies: ['BTC'],
  },
  {
    id: '37',
    name: 'Банк Решение',
    description: 'улица Ленина, 57, Витебск',
    coordinates: { lat: 55.198761, lng: 30.207443 },
    currencies: ['CAD', 'ARS', 'AUD', 'LRD'],
  },
  {
    id: '38',
    name: 'Беларусбанк',
    description: 'улица Богатырёва, 1А, Витебск',
    coordinates: { lat: 55.169867, lng: 30.257373 },
    currencies: ['CAD', 'ARS', 'CNY'],
  },
]
